### ISSUE TITLE
build errors when trying build sonic for otn VS image

### ISSUE THREAD

**Issue by erichaosu** [sonic-otn/sonic-buildimage#4]
#### Description

When building sonic-otn vs image, I got the following errors, this openssh-client(= 1:8.4p1-5+deb11u1) seems is not the one installed on my Linux(the build machine), my Linux is installed a different version of openssh-client.

Unpacking openssh-server (1:8.4p1-5+deb11u1) over (1:8.4p1-5+deb11u2) ...
dpkg: dependency problems prevent configuration of openssh-server:
 openssh-server depends on openssh-client (= 1:8.4p1-5+deb11u1); however:
  Version of openssh-client on system is 1:8.4p1-5+deb11u2.

dpkg: error processing package openssh-server (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openssh-server
+ clean_sys
+ sudo chroot ./fsroot-vs umount /sys/fs/cgroup/blkio /sys/fs/cgroup/cpu /sys/fs/cgroup/cpu,cpuacct /sys/fs/cgroup/cpuacct /sys/fs/cgroup/cpuset /sys/fs/cgroup/devices /sys/fs/cgroup/freezer /sys/fs/cgroup/hugetlb /sys/fs/cgroup/memory /sys/fs/cgroup/net_cls /sys/fs/cgroup/net_cls,net_prio /sys/fs/cgroup/net_prio /sys/fs/cgroup/perf_event /sys/fs/cgroup/pids /sys/fs/cgroup/rdma /sys/fs/cgroup/systemd /sys/fs/cgroup /sys
umount: /sys/fs/cgroup/cpu: no mount point specified.
umount: /sys/fs/cgroup/cpu,cpuacct: no mount point specified.
umount: /sys/fs/cgroup/cpuacct: no mount point specified.
umount: /sys/fs/cgroup/net_cls: no mount point specified.
umount: /sys/fs/cgroup/net_cls,net_prio: no mount point specified.
umount: /sys/fs/cgroup/net_prio: no mount point specified.
umount: /sys/fs/cgroup/systemd: no mount point specified.
+ true
+ true
+ sudo LANG=C chroot ./fsroot-vs umount /proc
+ true
[  FAIL LOG END  ] [ target/sonic-vs.img.gz ]
make: *** [slave.mk:1268: target/sonic-vs.img.gz] Error 1
Makefile.work:603: recipe for target 'target/sonic-vs.img.gz' failed
make[1]: *** [target/sonic-vs.img.gz] Error 2
make[1]: Leaving directory '/home/haosu/work/sonic-otn/sonic-buildimage'
Makefile:39: recipe for target 'target/sonic-vs.img.gz' failed
make: *** [target/sonic-vs.img.gz] Error 2

#### Steps to reproduce the issue:
1. make init
2.  make configure PLATFORM=vs
3. make target/sonic-vs.img.gz

#### Output of `show version`:

```
(paste your output here)
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by Weitang-Zheng** [comment]
Which sonic-otn buildimage branch you are working on?

**Comment by Weitang-Zheng** [comment]
If you are working on otn-legacy, there is a submit to fix the openssh version issue https://github.com/sonic-otn/sonic-buildimage/commit/c565c4b5323a95a4dbb72aa0672691cbc01f8ff8

**Comment by erichaosu** [comment]
I am working on branch otn_pre_202411. did a 'git pull' and restart build, same error:
Created symlink /etc/systemd/system/multi-user.target.wants/smartmontools.service -> /lib/systemd/system/smartmontools.service.
+ sudo dpkg --root=./fsroot-vs -i target/debs/bullseye/openssh-server_8.4p1-5+deb11u1_amd64.deb
dpkg: warning: downgrading openssh-server from 1:8.4p1-5+deb11u2 to 1:8.4p1-5+deb11u1
(Reading database ... 49475 files and directories currently installed.)
Preparing to unpack .../openssh-server_8.4p1-5+deb11u1_amd64.deb ...
Unpacking openssh-server (1:8.4p1-5+deb11u1) over (1:8.4p1-5+deb11u2) ...
dpkg: dependency problems prevent configuration of openssh-server:
 openssh-server depends on openssh-client (= 1:8.4p1-5+deb11u1); however:
  Version of openssh-client on system is 1:8.4p1-5+deb11u2.

dpkg: error processing package openssh-server (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 openssh-server

**Comment by sonic-otn** [comment]
The otn_pre_202411 branch doesn't contain any OTN implementation yet, it's a native sonic image. The sonic-otn group are working on merging otn_legacy implementations to the otn_pre_202411 branch.

If you want to test and play with sonic-otn system, please switch to the otn_legacy branch. And you can compile the system and refer to the [github actions](https://github.com/sonic-otn/sonic-buildimage/actions/runs/6740732168) and download the artifacts if you don't want build it.

For this compile issue, you can change the openssh-version  in `rules/openssh.mk` to
`
OPENSSH_VERSION = 8.4p1-5+deb11u2
`
